# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('c8295e143ec95aa1d3a37acbfa8fc817_MjM3MjE2MjAxMy0wNi0xNiAyMzozNDo1Ny45MjY2MjI')
  end)
end
